### ISSUE TITLE
Project.pbxproj files hash changes at every pod install

### ISSUE THREAD

**Issue by ste7en** [jamonholmgren/react-native-colo-loco#14]
Each time I run the react-native-colo-loco's `link_colocated_native_files` Podfile script it relinks files to my Xcode project resulting in a new entry in PBXBuildFile section of the project. This makes the project file to be tracked as changed by Git even if the native module did not change or a new one is linked.

**Comment by jamonholmgren** [comment]
I think to fix this, we'd need to have a way to tell if the files are already linked into Xcode and skip them. Might be fairly straightforward.

If we implemented that, we would probably want a way to force relinking.

**Comment by ste7en** [comment]
Hey @jamonholmgren 👋 PR #16 solves this issue
